if(~exist('line_width','var'))
    line_width=1;
end
if(~exist('title_font_size','var'))
    title_font_size=30;
end
if(~exist('axis_font_size','var'))
    axis_font_size=20;
end
if(~exist('x_axis_font_size','var'))
    x_axis_font_size=25;
end
if(~exist('y_axis_font_size','var'))
    y_axis_font_size=25;
end